### ISSUE TITLE
Snyk package and enrichment command runtime error on Windows

### ISSUE THREAD

**Issue by dck25** [snyk/parlay#37]
Running the example command below returns the following runtime error.  Snyk Token is set correctly.  I verified it is working on Linux via WSL.  A similar error occurs when trying to run snyk enrich for a CycloneDX SBOM.  I'm using this release https://github.com/snyk/parlay/releases/download/v0.1.5/parlay_Windows_x86_64.zip.

./parlay snyk package pkg:npm/sqliter@1.0.1

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x80a3ca]

goroutine 1 [running]:
github.com/snyk/parlay/lib/snyk.GetPackageVulnerabilities({{0xc00001e0f4, 0x3}, {0x0, 0x0}, {0xc00001e0f8, 0x7}, {0xc00001e100, 0x5}, {0xd89f00, 0x0, ...}, ...})
        /home/runner/work/parlay/parlay/lib/snyk/package.go:56 +0x1ca
github.com/snyk/parlay/internal/commands/snyk.NewPackageCommand.func1(0xc000005500?, {0xc000090140, 0x1?, 0x1?})
        /home/runner/work/parlay/parlay/internal/commands/snyk/packages.go:24 +0x1b8
github.com/spf13/cobra.(*Command).execute(0xc000005500, {0xc000090100, 0x1, 0x1})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xc000004300)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(0xc000054000?)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992 +0x19
main.main()
        /home/runner/work/parlay/parlay/main.go:26 +0x1e

**Comment by mcombuechen** [comment]
Hello @dck25 
thanks for reporting this. Can you confirm that this is still happening in the latest release? Thank you.

**Comment by mcombuechen** [comment]
Closing this due to inactivity. Should the issue still persist, please let us know.
